### ISSUE TITLE
make the action,_plugin a real library

### ISSUE THREAD

**Issue by drzraf** [sbitio/ansible-fail2ban#3]
I've a bootstrap role setting a few jails for fail2ban, and thus setting in it's `meta/mail.yml`:

``` yaml
dependencies:
  - { role: sbitmedia.fail2ban, fail2ban_.... ... }
```

But then I've some machine, which depends upon my bootstrap role which need to set more jails.
Sadly, in the current situation, they can't make use of the `action: fail2ban_jail` because:
1. in theory they should not be able to load again `sbitmedia.fail2ban` since it was already loaded during this run (without a `allow_duplicates`), see https://docs.ansible.com/playbooks_roles.html
2. anyway I _can_ have the bootstrap role to load sbitmedia.fail2ban, while adding:

``` yaml
  roles:
    - bootstrap   # has itself dependencies on sbitmedia.fail2ban
    - sbitmedia.fail2ban
```

... **but** in that case the second (and upper-level) call to sbitmedia.fail2ban will reinitialize my jail.local.
jail.local is just an ini_file, should we go that way?

**Comment by drzraf** [comment]
Precision:
The "reinitialize behavior" won't happen if the full playbook runs flawlessly, but will happens in case of eg: running only some tags (cases where the fail2ban role include inside the bootstrap role is **not** run **but** the later fail2ban role, in the top-level playbook, **is** run).

**Comment by jonhattan** [comment]
`fail2ban_jail` can't be a _real_ library because of how ansible is constructed, at least until ansible 1.6.  One of the differences between `library` and `action_plugin` is that `action_plugins` runs locally, within the ansible process, and libraries are processes run remotely on the target hosts. We need to run the code locally in order to have access to the data in yaml files and also to notify the service handler to restart when a jail changes. There's no way to do this in a _real_ library.

OTOH, ansible tags are basicly crap.

**Comment by drzraf** [comment]
Thank you for the clarification  jonhattan. I still have difficulties to understand the reason for limitation here. What things wouldn't be possible using a library? Does it mean that no library is able to upload files? Does Ansible 2.0 provides fixes or hopes?
Indeed, for example, the "mysql" module "dump" option needs a remote files.
But IMO roles duplications, variables passing and inheritances trickery is by far more annoying than some little workaround about uploading files.

Maybe the original subject about action_plugin/library is wrong. But at least, while sticking with the action_plugin it may be possible to avoid the original issue by avoid the need to "assemble" files.

This "assemble' thing is what makes the whole process very fragile since any playbook interruption or partial run (tags, ...) or role reload with different options would corrupt/rechange remote files. (That make the role "non-modular/non-reusable" right now).

**Comment by jonhattan** [comment]
The limitation is that we need access to role data (defaults, variables,..) in order to do the job (for example we need to know the default bantime, etc etc), and this data is not available in a module (a _real library_), because module code is copied and executed in the target host as a completely independent process. This is what I tried to explain in my previous comment. AFAIK the only way to do this in a module is to pass all data to the module.

On Ansible 2.0, I don't know what the changes are.

On "assemble", It was hard to implement, not an arbitrary decision. There was no alternative in not-so-old versions of fail2ban that doesn't support jail.d. That said, I'm fine with updating to support jail.d. PRs are welcome.
